%extracts EEG, treadmill, 2P imaging sync pulse, 
%sensory stim command pulses, and pupil cam exposures from raw Open Ephys
%data folder
%written for data recorded on in vivo imaging/ephys rig 

%saves file ***_ephys1.mat to experiment folder, using regexp to read 
%open ephys folder name for identifying information. Save path is pretty
%deep to accommodate folder structure expected by suite2p.

%file contains 3 structs: 
%   openEphysData --
%   Fields:
%       EEG:        single EEG channel data vector (downsampled to 2kHz)
%       EEGts:      time vector for EEG data
%       ballSpeed:  treadmill speed vector
%       ballTs:     time vector for treadmill speed data
%       puffTimes:  air puff times
%       EEGSSEP:    single EEG channel data vector for sensory-evoked
%                   potential analysis
%       whiskTimes: whisker piezo stim times
%       EEGWEP:     single EEG channel data vector for sensory-evoked
%                   potential analysis
%       camTimes:   time vector for pupil cam data
%       camFrame:   pupil video frame index associated with EEG record
%                   start
%       camFrameRate: pupil cam video frame rate
%   seizures1s -- seizure metrics for seizures with min 1s duration
%   seizures2s -- seizure metrics for seizures with min 2s duration

%dependencies:
%   load_open_ephys_data
%   dirr
%   modwtdetectseizures (/home/shared/matlabscripts)

function[]=ephys_extract_multifile(filelist)
openEphysData=struct;
seizures1s=struct;
seizures2s=struct;

for i=1:numel(filelist)
    %regexp to get experiment info (mouse number, expt number,
    %deep/superficial)
    file=filelist{i};
    fparts=regexp(file,'/','split');
    fnamepre=fparts{end};
    fdig=regexp(fnamepre,'\d');
    mousenum=fnamepre(fdig(1:3));
    if (fdig(5)-fdig(4))==1
        fieldnum=fnamepre(fdig(4:5));
    else
        fieldnum=fnamepre(fdig(4));
    end

    nparts=regexp(fnamepre,'_','split');
    isdeep=sum(strcmp(nparts,'deep'));

    if ~isdeep
        fname=strcat(mousenum,'Field',fieldnum,'_ephys1.mat');
    else
        fname=strcat(mousenum,'Field',fieldnum,'_deep_ephys1.mat');
    end

    %show file name based on regexp of open ephys data folder
    fprintf(fname)
    
    %read data from open ephys folder
    [ts,data,tspeed,dspeed,puffs,whisk,cam,camFrame]=read_open_ephys_axon(file);
    %default channels for seizure detection and sensory-evoked potentials
    eegChan=3;
    sepChan=1;
    wepChan=1;
    
    %give user the option to specify alternative EEG channel for seizure
    %analysis
    eegCheck=input('EEG channel for seizure detection?');
    if ~isempty(eegCheck)
        eegChan=eegCheck;
    end
    
    openEphysData.EEG=data(:,eegChan);
    openEphysData.EEGts=ts;
    openEphysData.ballSpeed=dspeed;
    openEphysData.ballTs=tspeed;

    %check for air puff command pulses
    %give user option to specify EEG channel for puff sensory-evoked 
    %potential (SEP)
    if ~isempty(puffs)
        sepCheck=input('EEG channel for puff SEP?');
        if ~isempty(sepCheck)
            sepChan=sepCheck;
        end
        openEphysData.puffTimes=puffs;
        openEphysData.EEGSSEP=data(:,sepChan);
    end
    
    %check for piezo whisker stim command pulses
    %give user option to specify EEG channel for whisker sensory-evoked
    %potential (SEP)
    if ~isempty(whisk)
        wepCheck=input('EEG channel for whisker SEP?');
        if ~isempty(wepCheck)
            wepChan=wepCheck;
        end
        openEphysData.whiskTimes=whisk;
        openEphysData.EEGWEP=data(:,wepChan);
    end
    openEphysData.camTimes=cam;
    openEphysData.camFrame=camFrame;
    openEphysData.camFrameRate=median(diff(cam));
    %close figures generated by data extraction functions
    close all
    
    %save ****_ephys1.mat file in experiment folder
    if ~isdeep
        spathpre=strcat('/home/michelle/TCAxons/MultiStream/',mousenum,'/',mousenum,'Field',fieldnum,'/');
        spath=strcat(spathpre,fname);
    else
        spathpre=strcat('/home/michelle/TCAxons/MultiStream/',mousenum,'/',mousenum,'Field',fieldnum,'_deep/');
        spath=strcat(spathpre,fname);
    end
    if ~isdir(spathpre)
        mkdir(spathpre)
    end
    save(spath,'openEphysData','file');

    sampRate=round(1/(ts(2)-ts(1)));
    seizures2s=modwtDetectSeizures(openEphysData.EEG,sampRate);
    seizures1s=modwtDetectSeizures(openEphysData.EEG,sampRate,'mindur',1);

    save(spath,'seizures1s','seizures2s','-append');
end